name: flutter_posts_app
description: A Flutter app to manage posts using Bloc and Fake Data Source.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.8
  meta: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
